#include <string.h>

#include "driver/gpio.h"
#include "driver/i2c.h"
#include "esp_err.h"
#include "esp_log.h"
#include "freertos/task.h"

#include "sdkconfig.h" // generated by "make menuconfig"

#include "ssd1366.h"
#include "font8x8_basic.h"

#define SDA_PIN 5
#define SCL_PIN 4

#define tag "SSD1306"

void i2c_master_init()
{
	i2c_config_t i2c_config = {
		.mode = I2C_MODE_MASTER,
		.sda_io_num = SDA_PIN,
		.scl_io_num = SCL_PIN,
		.sda_pullup_en = GPIO_PULLUP_ENABLE,
		.scl_pullup_en = GPIO_PULLUP_ENABLE,
		.master.clk_speed = 1000000
	};
	i2c_param_config(I2C_NUM_0, &i2c_config);
	i2c_driver_install(I2C_NUM_0, I2C_MODE_MASTER, 0, 0, 0);
}

void ssd1306_init() {
	esp_err_t espRc;
	i2c_cmd_handle_t cmd = i2c_cmd_link_create();

	i2c_master_start(cmd);	//start condition
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);	// SLA (0x3C) + WRITE_MODE (0x00) =  0x78 (0b01111000)
	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_CHARGE_PUMP, true);
	i2c_master_write_byte(cmd, 0x14, true);

	i2c_master_write_byte(cmd, OLED_CMD_SET_SEGMENT_REMAP, true); // reverse left-right mapping
	i2c_master_write_byte(cmd, OLED_CMD_SET_COM_SCAN_MODE, true); // reverse up-bottom mapping

	i2c_master_write_byte(cmd, OLED_CMD_DISPLAY_ON, true);
	i2c_master_stop(cmd);	//stop condition

	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "OLED configured successfully");
	} else {
		ESP_LOGE(tag, "OLED configuration failed. code: 0x%.2X", espRc);
	}
	i2c_cmd_link_delete(cmd);
}

void task_ssd1306_display_pattern(void *ignore) {
	i2c_cmd_handle_t cmd;

	for (uint8_t i = 0; i < 8; i++) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0xB0 | i, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		for (uint8_t j = 0; j < 128; j++) {
			i2c_master_write_byte(cmd, 0xFF >> (j % 8), true);
		}
		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
	}

	vTaskDelete(NULL);
}

void task_ssd1306_display_clear(void *ignore) {
	i2c_cmd_handle_t cmd;

	uint8_t zero[128] = {0};
	memset(zero, 0, sizeof(zero));
	for (uint8_t i = 0; i < 8; i++) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0xB0 | i, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, zero, 128, true);
		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
	}

	vTaskDelete(NULL);
}


void task_ssd1306_contrast(void *ignore) {
	i2c_cmd_handle_t cmd;

	uint8_t contrast = 0;
	uint8_t direction = 1;
	while (true) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
		i2c_master_write_byte(cmd, OLED_CMD_SET_CONTRAST, true);
		i2c_master_write_byte(cmd, contrast, true);
		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
		vTaskDelay(3/portTICK_PERIOD_MS);

		contrast += direction;
		if (contrast == 0xFF) { direction = -1; }
		if (contrast == 0x0) { direction = 1; }
	}
	vTaskDelete(NULL);
}

void task_ssd1306_scroll(void *ignore) {
	esp_err_t espRc;

	i2c_cmd_handle_t cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);	//Build commands

	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

	// vertical and horizontal scroll (manual page 29), following by 6 bytes
//	i2c_master_write_byte(cmd, 0x29, true); // command byte
//	i2c_master_write_byte(cmd, 0x00, true);	// A[7:0] dummy byte
//	i2c_master_write_byte(cmd, 0x00, true); // page0 as start page address
//	i2c_master_write_byte(cmd, 0x07, true); // set time interval between each frame, 0x07 = 2 frame is fastest
//	i2c_master_write_byte(cmd, 0x01, true); // page1 as end page address (the second row)
//	i2c_master_write_byte(cmd, 0x3F, true); // Set vertical scrolling offset as 1 row

	// Command 0xA3 - set vertical scroll area (p30)
//	i2c_master_write_byte(cmd, 0xA3, true);	//Command
//	i2c_master_write_byte(cmd, 0x20, true);	//Row address in top, it's 32nd line
//	i2c_master_write_byte(cmd, 0x40, true); //Set No. of rows in scroll area. it's 64 lines

	// Horizontal scroll (manual page 28), following by 6 bytes
	i2c_master_write_byte(cmd, 0x27, true); // command byte
	i2c_master_write_byte(cmd, 0x00, true);	// A[7:0] dummy byte
	i2c_master_write_byte(cmd, 0x01, true); // Start page: page1
	i2c_master_write_byte(cmd, 0x04, true); // set time interval between each frame, 0x04 = 3 frame is smooth
	i2c_master_write_byte(cmd, 0x01, true); // End page: page8
	i2c_master_write_byte(cmd, 0x00, true);	// E[7:0] dummy byte, must be 0x00
	i2c_master_write_byte(cmd, 0xFF, true);	// F[7:0] dummy byte, must be 0xFF

	i2c_master_write_byte(cmd, 0x2F, true); // activate scroll (p29)

	i2c_master_stop(cmd);
	espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);	//send commands

	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "Scroll command succeeded");
	} else {
		ESP_LOGE(tag, "Scroll command failed. code: 0x%.2X", espRc);
	}

	i2c_cmd_link_delete(cmd);

	vTaskDelete(NULL);
}

void task_ssd1306_display_text(const void *arg_text) {
	char *text = (char*)arg_text;
	uint8_t text_len = strlen(text);

	i2c_cmd_handle_t cmd;

	uint8_t cur_page = 0;

	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd, 0x00, true); // reset column
	i2c_master_write_byte(cmd, 0x10, true);
	i2c_master_write_byte(cmd, 0xB0 | cur_page, true); // reset page

	i2c_master_stop(cmd);
	i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
	i2c_cmd_link_delete(cmd);

	for (uint8_t i = 0; i < text_len; i++) {
		if (text[i] == '\n') {
			cmd = i2c_cmd_link_create();	//Build commands
			i2c_master_start(cmd);
			i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

			i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
			i2c_master_write_byte(cmd, 0x00, true); //Set Lower Column Start Address for Page Addressing Mode (00h~0Fh), from page 1/column 1
			i2c_master_write_byte(cmd, 0x10, true); //Set Higher Column Start Address for Page Addressing Mode (10h~1Fh), from page 8/column 1
			i2c_master_write_byte(cmd, 0xB0 | ++cur_page, true); // increment page	(Set Page Start Address for Page Addressing Mode (B0h~B7h)

			i2c_master_stop(cmd);
			i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);	// Send commands
			i2c_cmd_link_delete(cmd);
		} else {
			cmd = i2c_cmd_link_create();
			i2c_master_start(cmd);
			i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

			i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
			i2c_master_write(cmd, font8x8_basic_tr[(uint8_t)text[i]], 8, true);

			i2c_master_stop(cmd);
			i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
			i2c_cmd_link_delete(cmd);
		}
	}

	vTaskDelete(NULL);
}

void ssd3316_println(int page_num, int column_num, const void* arg_text)
{
	char *text = (char*)arg_text;
	uint8_t text_len = strlen(text);
	i2c_cmd_handle_t cmd;

	//Send command for configuration
	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

	//The commands stream is starting
	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

	//Set to horizontal mode
	i2c_master_write_byte(cmd, 0x20, true);	//command, set address mode
	i2c_master_write_byte(cmd, 0b00, true);	//command param: Horizontal address mode ( 00b )

	//Set page
	i2c_master_write_byte(cmd, 0x22, true); // command, set page address
	i2c_master_write_byte(cmd, page_num, true); //command param: Set start page
	i2c_master_write_byte(cmd, 7, true); //command param: set end page

	//Set column
	i2c_master_write_byte(cmd, 0x21, true); //command, set column address
	i2c_master_write_byte(cmd, column_num*8, true); //command param: start column
	i2c_master_write_byte(cmd, 127, true); //command param: end column

	i2c_master_stop(cmd);
	i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);	//wait for 10ms
	i2c_cmd_link_delete(cmd);

	//Send text data
	for (uint8_t i = 0; i < text_len; i++)
	{
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, font8x8_basic_tr[(uint8_t)text[i]], 8, true);

		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
	}
}

void ssd1306_scroll_print(int page_num, const void* arg_text)
{
	char *text = (char*)arg_text;
	uint8_t text_len = strlen(text);

	uint8_t* buf = (uint8_t*)malloc(1024);
	memset(buf,0,1024);

	//memcpy( buf+3*128, font8x8_basic_tr[(uint8_t)'8'],8*16);

	//Send text data
	for(uint8_t i=0;i<=8;i++)
	{
		i2c_cmd_handle_t cmd;

		//Send command for configuration
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

		//The commands stream is starting
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);

		//Set to horizontal mode
		i2c_master_write_byte(cmd, 0x20, true);	//command, set address mode
		i2c_master_write_byte(cmd, 0b00, true);	//command param: Horizontal address mode ( 00b )

		//Set page
		i2c_master_write_byte(cmd, 0x22, true); // command, set page address
		i2c_master_write_byte(cmd, 0, true); //command param: Set start page
		i2c_master_write_byte(cmd, 7, true); //command param: set end page

		//Set column
		i2c_master_write_byte(cmd, 0x21, true); //command, set column address
		i2c_master_write_byte(cmd, 0, true); //command param: start column
		i2c_master_write_byte(cmd, 127, true); //command param: end column

		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);	//wait for 10ms
		i2c_cmd_link_delete(cmd);

		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, buf, 1024, true);

		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);

		int k=0;
		for(uint8_t j=0;j<(text_len*8);j++)
		{
			uint8_t c = *(font8x8_basic_tr[(uint8_t)text[j/8]]+(uint8_t)k);
			//ESP_LOGI(tag,"char is 0x%02x",c);
			if( (c>>i) & 0b00000001 )
			{
				buf[page_num*128+j] = (buf[page_num*128+j]>>1) | 0b10000000;
			}
			else
			{
				buf[page_num*128+j] = (buf[page_num*128+j]>>1);
			}

			k++;
			if (k==8)
			{
				k=0;
			}

		}

		vTaskDelay(50/portTICK_PERIOD_MS);
	}
}

void ssd1306_contrast(int arg_contrast)
{
	i2c_cmd_handle_t cmd;
	cmd = i2c_cmd_link_create();
	i2c_master_start(cmd);
	i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

	i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_STREAM, true);
	i2c_master_write_byte(cmd, OLED_CMD_SET_CONTRAST, true); // Command: set contrast
	i2c_master_write_byte(cmd, arg_contrast, true);	// contrast from 1 to 256

	i2c_master_stop(cmd);
	esp_err_t espRc = i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);	//send commands

	if (espRc == ESP_OK) {
		ESP_LOGI(tag, "Contract command succeeded: %d", arg_contrast);
	} else {
		ESP_LOGE(tag, "Contract command failed. code: 0x%.2X", espRc);
	}

	i2c_cmd_link_delete(cmd);
}

void ssd1306_clear()
{
	i2c_cmd_handle_t cmd;

	uint8_t zero[128]={0}; //fill 0
	for (uint8_t i = 0; i < 8; i++) {
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);
		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0xB0 | i, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_DATA_STREAM, true);
		i2c_master_write(cmd, zero, 128, true);
		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);
		i2c_cmd_link_delete(cmd);
	}

}
void app_main(void)
{
	i2c_master_init();
	ssd1306_init();

	//xTaskCreate(&task_ssd1306_display_pattern, "ssd1306_display_pattern",  2048, NULL, 6, NULL);


//	xTaskCreate(&task_ssd1306_display_clear, "ssd1306_display_clear",  2048, NULL, 6, NULL);
//	vTaskDelay(1000/portTICK_PERIOD_MS);

//	xTaskCreate(&task_ssd1306_display_text, "ssd1306_display_text",  2048,
//		(void *)"Hello world!\nMulitine is OK!\nAnother line", 6, NULL);

//	vTaskDelay(500/portTICK_PERIOD_MS);
//	xTaskCreate(&task_ssd1306_contrast, "ssid1306_contrast", 2048, NULL, 6, NULL);

//	vTaskDelay(500/portTICK_PERIOD_MS);
//	xTaskCreate(&task_ssd1306_scroll, "ssid1306_scroll", 2048, NULL, 6, NULL);


	ssd1306_clear();
	//ssd3316_println(3,0,"123456789012345678901234567890");

	/*
	char* text[255];
	while(true)
	{
		for(int i=1;i<=256;i++)
		{
			ssd1306_contrast(i);
			sprintf(text, " Contrast: %d ", i);
			ssd3316_println(3,0, text);
			vTaskDelay(10/portTICK_PERIOD_MS);
		}

		for(int i=255;i>=1;i--)
		{
			ssd1306_contrast(i);
			sprintf(text, " Contrast: %d ", i);
			ssd3316_println(3,0, text);
			vTaskDelay(10/portTICK_PERIOD_MS);
		}
	}
	*/

	/*// Start specific line
	for(int i=0;i<=63;i++)
	{
		i2c_cmd_handle_t cmd;
		cmd = i2c_cmd_link_create();
		i2c_master_start(cmd);
		i2c_master_write_byte(cmd, (OLED_I2C_ADDRESS << 1) | I2C_MASTER_WRITE, true);

		i2c_master_write_byte(cmd, OLED_CONTROL_BYTE_CMD_SINGLE, true);
		i2c_master_write_byte(cmd, 0x40 | i, true);

		i2c_master_stop(cmd);
		i2c_master_cmd_begin(I2C_NUM_0, cmd, 10/portTICK_PERIOD_MS);	//send commands

		ESP_LOGI(tag, "Display line at %d", i);

		i2c_cmd_link_delete(cmd);

		if(i==32)
		{
			ssd3316_println(3,3,"This is new World!");
		}
		vTaskDelay(100/portTICK_PERIOD_MS);
	}
	*/

	while(true)
	{
		ssd1306_scroll_print(3, "Hello World!              ");
		vTaskDelay(1000/portTICK_PERIOD_MS);
		ssd1306_scroll_print(3, "ESP32-IDF programming     ");
		vTaskDelay(1000/portTICK_PERIOD_MS);
		ssd1306_scroll_print(3, "SSD1306 display demo......");
		vTaskDelay(1000/portTICK_PERIOD_MS);
		ssd1306_scroll_print(3, "run ssd1306_scroll_print()");
		vTaskDelay(1000/portTICK_PERIOD_MS);
	}
}

